// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf-eibvYpKrntZUk3Qtr-CZ1M8PCc83V0',
    appId: '1:148835504848:web:d22ddfaadcb290cdeb84d5',
    messagingSenderId: '148835504848',
    projectId: 'shelfswap-36603',
    authDomain: 'shelfswap-36603.firebaseapp.com',
    storageBucket: 'shelfswap-36603.firebasestorage.app',
    measurementId: 'G-X7C8W1MHF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Tmlr9GKMCrNC3zI811Fe2aTL0RBHUB4',
    appId: '1:148835504848:android:ac2b9532678a8c20eb84d5',
    messagingSenderId: '148835504848',
    projectId: 'shelfswap-36603',
    storageBucket: 'shelfswap-36603.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiK-qYEl4XTlmh-5DtLMxqSu8pZzKzdGg',
    appId: '1:148835504848:ios:04b79746a7e54ca3eb84d5',
    messagingSenderId: '148835504848',
    projectId: 'shelfswap-36603',
    storageBucket: 'shelfswap-36603.firebasestorage.app',
    iosBundleId: 'com.example.shelfswapFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiK-qYEl4XTlmh-5DtLMxqSu8pZzKzdGg',
    appId: '1:148835504848:ios:04b79746a7e54ca3eb84d5',
    messagingSenderId: '148835504848',
    projectId: 'shelfswap-36603',
    storageBucket: 'shelfswap-36603.firebasestorage.app',
    iosBundleId: 'com.example.shelfswapFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf-eibvYpKrntZUk3Qtr-CZ1M8PCc83V0',
    appId: '1:148835504848:web:451963a2552c6d26eb84d5',
    messagingSenderId: '148835504848',
    projectId: 'shelfswap-36603',
    authDomain: 'shelfswap-36603.firebaseapp.com',
    storageBucket: 'shelfswap-36603.firebasestorage.app',
    measurementId: 'G-ZFLBFQNVJJ',
  );
}
